name = "vuejshomepage"
type = "webpack"
account_id = "4ee4dc20e660cf6bc08c1383352f011a"
workers_dev = false
route = "*.warenghem.com/*"
zone_id = "97bc3e5922228882f8ca3e1e0af3839f"

[site]
bucket = "./dist"
entry-point = "workers-site"